DROP TABLE IF EXISTS public.apartment_table;
DROP TABLE IF EXISTS public.Customers;
DROP TABLE IF EXISTS public.Categories;
DROP TABLE IF EXISTS public.Employees;
DROP TABLE IF EXISTS public.OrderDetails;
DROP TABLE IF EXISTS public.Orders;
DROP TABLE IF EXISTS public.Products;
DROP TABLE IF EXISTS public.Shippers;
DROP TABLE IF EXISTS public.Suppliers;